backend: drop unconditional and unused <libinput.h>
After 70fb21c35ba4 made libinput optional the include prevents
building without libinput package installed.

backend/backend.c:4:10: fatal error: 'libinput.h' file not found
 #include <libinput.h>
          ^~~~~~~~~~~~